language: scala

sudo: required

services:
- docker

scala:
- 2.12.10
- 2.13.1

jdk:
- openjdk8

stages:
- name: test
- name: release
  if: "(branch = master AND type = push) OR (tag IS present)"

# Integration tests uses secrets and are not available on builds for pull requests
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker-compose run --rm sbt -Dsbt.ci=true ++$TRAVIS_SCALA_VERSION clean scalafmtCheckAll scalafmtSbtCheck docs/mdoc coverage "scalafix --check; testOnly * -- -l blobstore.IntegrationTest" coverageReport; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker-compose run --rm sbt -Dsbt.ci=true ++$TRAVIS_SCALA_VERSION clean scalafmtCheckAll scalafmtSbtCheck docs/mdoc coverage "scalafix --check; test" coverageReport; fi'
  - bash <(curl -s https://codecov.io/bash) -F "scala_${TRAVIS_SCALA_VERSION//[.-]/_}"

jobs:
  include:
  - stage: release
    script:
    - sbt ci-release
    - sbt docs/mdoc
    - ci/doc-push.sh

before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi

after_script:
- docker-compose rm -svf

before_cache:
- sudo chown -R $(id -u):$(id -g) $HOME
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
- rm -rf $HOME/.ivy2/local

cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier"

after_success: sudo chown -R $HOME $(id -u):$(id -g)

before_install:
- git fetch --tags
- openssl aes-256-cbc -K $encrypted_980a2da0c0ea_key -iv $encrypted_980a2da0c0ea_iv -in box/src/test/resources/box_appkey.json.enc -out box/src/test/resources/box_appkey.json -d

env:
  global:
  # Codecov token
  - secure: jF9Qop8eI+tOYjBp1u7ETmwDRFOCADzNavgp+OTkWEAGDKTH5ebkfKbbd3sQKVABgqivDdmcWWiB16D7QI5oueQ78XqlcjtWYAl/T4Mvaq6eBu6rgz7dTFMFQJYQwruqGyia7gIWGeaGZ//Ng3ngNx+x48p2J+Bu4IQG9T/HOQ2ohitNgK6AD/Ao/TLnZVR57g9DIyI8su1jDD/4Lb6iXx2uQ9EBFeqfHBRb2EMD9VwF+Ka6O7iFRRxiothJxRwcZ+VOkBadT8pS2U0+U/RPMkjLkcnD/8nXFbv9/moJMi3hIk2HP8INFTsQcJi92bX/3KIz4n+FgnUeb0QuFkxyOlM1/M5+1u6rsjp64xa4f8kbN81hLFP09jN2gvWtbwRweDOlJaHEwlRCGRETHNG0EKa2LHxcw6sN9uFyi9+0u9Sy/tlN0xaE2hfMmL4ggxcFTSSk7EG8aU0lHmIOGk6Gk/NbKe1z4sxsuJf5twBCAmGST4C/oJwwLauWXGYZo+nVm9/UpK4ccDg+jNUWN0+iO8he+MpRYoX1/C1vcH6K5WlMAjBGgsEkyF6nmSEnmXxm1L9O+LReyf3gYFpSrHY6h5S6ZnQvO5vKsV0CY/zf0J2Q3fURXR4mwlaxzSuZEo8eQt5rEMQEF0sGYK4bCnZZdLjrNYp0LFArM3/Fge53zG0=
  # Sonatype username and password
  - secure: Ir/FC49bV3xHMtNFwaN/rFwQsBYCaPYLei02zisKYDL9CYNR1Wpx8kFjagU6XG4DOdTygli45Q6D7RLzZWkqvnWtnHW9XMC2KZo/sOD9bTgGmKpf2Q+SyCDNIyoyzcigpXrDLmCyLLKvC5nRgaJCv21dwgFokW5aEpLKh88inVHR+Nuv0yZtmRbzf2CsTq2fV8wOYSzEtsV1W4/dSg0oH6tTssFFX782EC4/AH5TdphA1i2DqFOsu064xl+Vvhl8r27cz+MT1snqTB6gjOVCelIavr4p9rnJZv+su7bQdsYCCXucCNS8xhmR63OBNYIejP5Op6MMf3BKBatjlVdJrFLj2U33ZQpCfnHJzc8NebnzipbU8pLT+0Mg89P7kesKIP+o80B3DyducqHECH86Ha/VVDHOUItRLzUc4sPVc/nJz6P0VGiDElds2DWq0UvEAWQ1p+2ZgvZ4Uf6j5KYC2ssvOjs6F1u5UfwRRSWX/o2npar0zC0/DYiLyr8D97X8AU+ywb6f1t0Zptbom4bWUCGRwUOfGNKS8HMTEaD++011Y/4yxuz/35gMZ9Klz6hgsZI32BAzoWdC85OkWTUfPjqHNp7Q446Goy+ktGTX5YL+OFT1ROsvclwV4QFGDQjErpX0d8K/dlL8Ctkb7j7TAjPv7m1NbaJfg8q0XW+k99Y=
  - secure: l1b6TJKc5xF6p43huLuYwkPZwFMr072+D3hhPNM/c78RMrmD/7aGOT/yf1S0Y+00BJlvHRSad2wWm5yd21vZPczeuAZ2rzl1/yBYfdlHq8Q7Ap7dNnB37zl7Y5hEMpPB0YLbGmo9kTuprggR/o/IUffnSTQjaCXRh5TbDIu6wvcQgTTukGRmLMCGJhF3uxw4Afsgqa3RrtIQgHcNSQVg0zeor5jgtBoKgea1sFzYgpKfZFdWHqa7faW3Ku5I0PiH1EEHI72KxV77SsuEJJ8PKb/WGeTgM449K/pzxwCN0tyxXANk9lZFq0R7g9h5J1fS8CRmAP7maRfbmvNVUazpLVL0QxHK9D0l4x/GjH41A2yAeHtDOIOQcitdTkI4wzqn9OC3JdUExoj2G9ZFPAWOqnagZiP6wIos65sI2w7JK+xOyZUG1nspionUykaDKZNo/Dc7gngvZt2geZCMARek7TJ+3zTjWkuMFdKYICqtc/jZjcMPgwBym6p3HgROegSeuzh8Wsz86QPHlTp5BquHDh0XgIdO+Y4IwwygX4xLzUE87w5aI3mdCW5HV0a4M2TcBLT+/2ZKyeGL3KqUAWSSZEjMSQ1YghdGa31lShH77g5EEAjsHKL1FhYww4jZSOv5vC35PIP+CfITruQQX2Y77n+I1MCO3u2Zci3bEA/HpQY=
  # S3 integration test
  - secure: JegqRRd8tQa3e+Ihd3JssliWAVFGOk42tYIMdA/XFp+eU+WyiLRRf9Ta314cAynzau0HSldWobIRlA1yf+l0t7hN8pIbEz8tbDCl9ePg6qb4YPDOnsyZmGuQqT4S6IZE7OwUq4YFCQUal+iWlBmzOf0W9V59CHhFbYqAEdoP716Vmu8Jo9hcc8+DYiqro/bL0uWso06BhwdI10O37hdU9csMuHplWGp/ovrT/mjBfiluOnlfFtY/NYS94wpFLIUy1EA5S+E9xX/LxnrWtxiQvzqNp54X1Tyo3lkhlwEugwo6sHjlsoIM6HPSmSyt7n9ySnKtdT+GIC5jrMjeW5K4mM0Ox/+CpI5yQoohOCg+RYmw/A3UHA719zF2Ghk6GGS71qops/bqijFSObGW3Beofd8IAdGOdMr4Rk1jDgDvC5bIl39cKp3DQts8vFsPF9Aa4x94TC64p8q4+IdsVXX4y+Fr1CpX4VCDKN1VCyVFD10vqF9TRWpOxYOsEf3FAJ/GlBKMYUnxBdMsrKF3A2H0Jp0uSkpG9BJjRz3N0iO6pF8WNPOrPyRRv5M0EPajhvNu3fMXDGiJoDBnKXaZOJu6rpzIynLoAc7F5yyURdfeGkCk8OiHgw8wRg/iIH9BUrZCQqNdbEEVIAKPN1h4KELB0WFnkxVFBfigL5DzorzhIXo=
  - secure: D1SjAgzS45S+rXCp+T8yuElK01ETOsDAVDyFWWKOW/YjqeryjFT07W/1+CIi8SnXx3Frjz0ydwKi2n15+8ElRTBXmhYQYV2zIFof3CD7LqF0Zwi4SwOGhDN7WrEKS0SxtTYwB3g9XA7pEPZ/OW5L1dll1HO1f23dEIvBJpZRz5QYHORq3Cxki0UDNDLsYMiGwM7sT0oQr6lFNLo02nwzQWUs2ffih+lHCWT4+yp/OJwEHeS0AgdVlpsmrjBCfum35sYLLzDn0vVRSgzCqvbez1Wc3IKeAAsG46Rv92smE9u29Ehum+RiuE1xjGaVTdZRIS7iQgNZAc7KVvo8JPu35v8MCPf/bl3J0yaiAZGCoIf8lM2GxHXzCitIimF71N4pBbm2BqEnbwAXtH7asDsg0TyZ/bkEfuHm3iQQaEl9Ojm5pe/ciQruWozsLIj7mlCAfw033AT/FSiiPyeKw7HD0OIM+m6SkMOdcc1W53qXZXQg4j2XVsVPKtZEcJWNA/0v3h+la/JIxZq3FctJ7/RqinsGOUCYf8KjITZT5C+iO/iFGTiN/eWEPlU4mDNXnSUlwURHQGFFMzxLujUITePs4e0JTCpuS/0iaa/wk6/Ygoqym4z2g4QzQgiGN2htPEUW+fGmDaf8j6m2jWXd7VYzJFfI6KZcevQGM1X5OexP8ig=
  - secure: a6lnTWmW377jh1VlT4P/sQxuj2+QdqUCFEyxxNxjNiXLUVHXNRBDRQDHiunjvuqH8xdgzJHAFhi+hq5dGVgpgWctG66/y5Yee+BomxAB/3KgoMBE/5aZNMjqVK1PjOh411os+99JWYbCWw0xZs/YrLdUm303JhSwL2CjBxlPpSm+OGHd68ZUH4zgazslxfgos731lT3UzJ/LLKHWZPkI8p+G6/8EMm9kR4LFeFQv/xyNE/H3dgEQLrKlMxKTFxE7PKe9H9MvXtTt+CjeZ+uHkJPXxsxFInf1sSMn5/2CsI4LskXxP9yrPzMhuhpdBrsT9xxG1vi4fmtu0s/Rh9lMpZjBFpC6jUG6SkU2tbRcxacu7eO/AsYiHn2ylISGaorOEp3LkYa4caLnhCQHQqHNTyn/VnARq5zUKJIIaIu/dCOjc6j9FVoSMP+TIZJY6japxtoTdenKyZXWqFM/fjnCS0DOGeLAAjkHP3K4r8BoBm/qxs6MPBHj74fGretIzwlCJFaKlsCl2lUPeDvTaPsnHRhf9LUMMw8gT+ANPPAES0u72GIVNVIkSJWGwlgwyZWJxAqnXdEd99hDjm0IrN2HG84iRQHTPJ6Z85WPduk9eIcrDqzFoeN8LCJmsgolaJMzwOfyE6YQZB19dpaPRLbfzyn6E/rLpEQxQjVTdO0HpAc=
